-- You probably always want to set this in your vim file
vim.opt.background = 'dark'
vim.g.colors_name = 'candyland'

-- By setting our module to nil, we clear lua's cache,
-- which means the require ahead will *always* occur.
--
-- This isn't strictly required but it can be a useful trick if you are
-- incrementally editing your config a lot and want to be sure your themes
-- changes are being picked up without restarting neovim.
--
-- Note if you're working in on your theme and have :Lushify'd the buffer,
-- your changes will be applied with our without the following line.
--
-- The performance impact of this call can be measured in the hundreds of
-- *nanoseconds* and such could be considered "production safe".
package.loaded['lush_theme.candyland'] = nil

-- include our theme file and pass it to lush to apply
require('lush')(require('lush_theme.candyland'))

local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#c0caf5", bg = "#251a34"},
NvimSpacing = {link = "Normal"},
NvimTreePopup = {link = "Normal"},
Bold = {bold = true},
markdownBold = {link = "Bold"},
["@text.strong"] = {link = "Bold"},
BookmarkAnnotationSign = {fg = "#e0af68"},
BookmarkSign = {fg = "#536c9e"},
Boolean = {fg = "#ff8994", bold = true},
BufferCurrent = {fg = "#c0caf5", bg = "#3b4261"},
BufferCurrentIndex = {fg = "#0db9d7", bg = "#3b4261"},
BufferCurrentMod = {fg = "#e0af68", bg = "#3b4261"},
BufferCurrentSign = {fg = "#0db9d7", bg = "#3b4261"},
BufferCurrentTarget = {fg = "#f7768e", bg = "#3b4261", bold = true},
BufferInactive = {fg = "#737aa2", bg = "#16161e"},
BufferInactiveIndex = {fg = "#737aa2", bg = "#16161e"},
BufferInactiveMod = {fg = "#a58354", bg = "#16161e"},
BufferInactiveSign = {fg = "#2d59a1", bg = "#16161e"},
BufferInactiveTarget = {fg = "#f7768e", bg = "#16161e", bold = true},
BufferLineBackground = {fg = "#565f89", italic = true},
BufferLineBuffer = {fg = "#565f89"},
BufferLineBufferSelected = {fg = "#c0caf5", bold = true, italic = true},
BufferLineBufferVisible = {fg = "#565f89"},
BufferLineCloseButton = {fg = "#565f89"},
BufferLineCloseButtonSelected = {fg = "#c0caf5"},
BufferLineCloseButtonVisible = {fg = "#565f89"},
BufferLineDevIconLua = {fg = "#51a0cf"},
BufferLineDevIconLuaSelected = {fg = "#51a0cf"},
BufferLineDiagnostic = {fg = "#404766"},
BufferLineDiagnosticSelected = {fg = "#9097b7", bold = true, italic = true},
BufferLineDiagnosticVisible = {fg = "#404766"},
BufferLineDuplicate = {fg = "#515a82", italic = true},
BufferLineDuplicateSelected = {fg = "#515a82", italic = true},
BufferLineDuplicateVisible = {fg = "#515a82", italic = true},
BufferLineError = {fg = "#565f89", sp = "#db4b4b"},
BufferLineErrorDiagnostic = {fg = "#404766", sp = "#a43838"},
BufferLineErrorDiagnosticSelected = {fg = "#a43838", sp = "#a43838", bold = true, italic = true},
BufferLineErrorDiagnosticVisible = {fg = "#404766"},
BufferLineErrorSelected = {fg = "#db4b4b", sp = "#db4b4b", bold = true, italic = true},
BufferLineErrorVisible = {fg = "#565f89"},
BufferLineFill = {fg = "#565f89"},
BufferLineGroupLabel = {bg = "#565f89"},
BufferLineGroupSeparator = {fg = "#565f89"},
BufferLineHint = {fg = "#565f89", sp = "#1abc9c"},
BufferLineHintDiagnostic = {fg = "#404766", sp = "#138d75"},
BufferLineHintDiagnosticSelected = {fg = "#138d75", sp = "#138d75", bold = true, italic = true},
BufferLineHintDiagnosticVisible = {fg = "#404766"},
BufferLineHintSelected = {fg = "#1abc9c", sp = "#1abc9c", bold = true, italic = true},
BufferLineHintVisible = {fg = "#565f89"},
BufferLineIndicatorSelected = {fg = "#536c9e"},
BufferLineIndicatorVisible = {},
BufferLineInfo = {fg = "#565f89", sp = "#0db9d7"},
BufferLineInfoDiagnostic = {fg = "#404766", sp = "#098aa1"},
BufferLineInfoDiagnosticSelected = {fg = "#098aa1", sp = "#098aa1", bold = true, italic = true},
BufferLineInfoDiagnosticVisible = {fg = "#404766"},
BufferLineInfoSelected = {fg = "#0db9d7", sp = "#0db9d7", bold = true, italic = true},
BufferLineInfoVisible = {fg = "#565f89"},
BufferLineModified = {fg = "#ffcfe8"},
BufferLineModifiedSelected = {fg = "#ffcfe8"},
BufferLineModifiedVisible = {fg = "#ffcfe8"},
BufferLineNumbers = {fg = "#565f89"},
BufferLineNumbersSelected = {fg = "#c0caf5", bold = true, italic = true},
BufferLineNumbersVisible = {fg = "#565f89"},
BufferLineOffsetSeparator = {fg = "#000000"},
BufferLinePick = {fg = "#db4b4b", bold = true, italic = true},
BufferLinePickSelected = {fg = "#db4b4b", bold = true, italic = true},
BufferLinePickVisible = {fg = "#db4b4b", bold = true, italic = true},
BufferLineSeparator = {},
BufferLineSeparatorSelected = {},
BufferLineSeparatorVisible = {},
BufferLineTab = {fg = "#565f89"},
BufferLineTabClose = {fg = "#565f89"},
BufferLineTabSelected = {fg = "#7aa2f7"},
BufferLineTabSeparator = {},
BufferLineTabSeparatorSelected = {},
BufferLineWarning = {fg = "#565f89", sp = "#e0af68"},
BufferLineWarningDiagnostic = {fg = "#404766", sp = "#a8834e"},
BufferLineWarningDiagnosticSelected = {fg = "#a8834e", sp = "#a8834e", bold = true, italic = true},
BufferLineWarningDiagnosticVisible = {fg = "#404766"},
BufferLineWarningSelected = {fg = "#e0af68", sp = "#e0af68", bold = true, italic = true},
BufferLineWarningVisible = {fg = "#565f89"},
BufferTabpage = {fg = "#2d59a1", bg = "#16161e"},
BufferTabpages = {bg = "#16161e"},
BufferVisible = {fg = "#c0caf5", bg = "#16161e"},
BufferVisibleIndex = {fg = "#0db9d7", bg = "#16161e"},
BufferVisibleMod = {fg = "#e0af68", bg = "#16161e"},
BufferVisibleSign = {fg = "#0db9d7", bg = "#16161e"},
BufferVisibleTarget = {fg = "#f7768e", bg = "#16161e", bold = true},
["@character"] = {link = "Character"},
CmpDocumentation = {fg = "#c0caf5", bg = "#16161e"},
CmpDocumentationBorder = {fg = "#2d59a1", bg = "#16161e"},
CmpItemAbbr = {fg = "#c0caf5"},
CmpItemAbbrDefault = {fg = "#c0caf5"},
CmpItemAbbrDeprecated = {fg = "#3b4261", strikethrough = true},
CmpItemAbbrDeprecatedDefault = {fg = "#565f89"},
CmpItemAbbrMatch = {fg = "#2ac3de"},
CmpItemAbbrMatchDefault = {fg = "#c0caf5"},
CmpItemAbbrMatchFuzzy = {fg = "#1abc9c"},
CmpItemAbbrMatchFuzzyDefault = {fg = "#c0caf5"},
CmpItemKind = {},
CmpItemKindClassDefault = {link = "CmpItemKind"},
CmpItemKindColorDefault = {link = "CmpItemKind"},
CmpItemKindConstantDefault = {link = "CmpItemKind"},
CmpItemKindConstructorDefault = {link = "CmpItemKind"},
CmpItemKindEnumDefault = {link = "CmpItemKind"},
CmpItemKindEnumMemberDefault = {link = "CmpItemKind"},
CmpItemKindEventDefault = {link = "CmpItemKind"},
CmpItemKindFieldDefault = {link = "CmpItemKind"},
CmpItemKindFileDefault = {link = "CmpItemKind"},
CmpItemKindFolderDefault = {link = "CmpItemKind"},
CmpItemKindFunctionDefault = {link = "CmpItemKind"},
CmpItemKindInterfaceDefault = {link = "CmpItemKind"},
CmpItemKindKeywordDefault = {link = "CmpItemKind"},
CmpItemKindMethodDefault = {link = "CmpItemKind"},
CmpItemKindModuleDefault = {link = "CmpItemKind"},
CmpItemKindOperatorDefault = {link = "CmpItemKind"},
CmpItemKindPropertyDefault = {link = "CmpItemKind"},
CmpItemKindReferenceDefault = {link = "CmpItemKind"},
CmpItemKindSnippetDefault = {link = "CmpItemKind"},
CmpItemKindStructDefault = {link = "CmpItemKind"},
CmpItemKindTextDefault = {link = "CmpItemKind"},
CmpItemKindTypeParameterDefault = {link = "CmpItemKind"},
CmpItemKindUnitDefault = {link = "CmpItemKind"},
CmpItemKindValueDefault = {link = "CmpItemKind"},
CmpItemKindVariableDefault = {link = "CmpItemKind"},
CmpItemKindClass = {fg = "#ff9e64"},
CmpItemKindColor = {fg = "#c0caf5"},
CmpItemKindConstant = {fg = "#bb9af7"},
CmpItemKindConstructor = {fg = "#7aa2f7"},
CmpItemKindCopilot = {fg = "#6cc644"},
CmpItemKindCrate = {fg = "#f64d00"},
CmpItemKindDefault = {fg = "#85dff8"},
CmpItemKindDefaultc = {fg = "#a9b1d6"},
CmpItemKindEmoji = {fg = "#fde030"},
CmpItemKindEnum = {fg = "#ff9e64"},
CmpItemKindEnumMember = {fg = "#73daca"},
CmpItemKindEvent = {fg = "#ff9e64"},
CmpItemKindField = {fg = "#73daca"},
CmpItemKindFile = {fg = "#c0caf5"},
CmpItemKindFolder = {fg = "#c0caf5"},
CmpItemKindFunction = {fg = "#7aa2f7"},
CmpItemKindInterface = {fg = "#ff9e64"},
CmpItemKindKeyword = {fg = "#7dcfff"},
CmpItemKindMethod = {fg = "#7aa2f7"},
CmpItemKindModule = {fg = "#e0af68"},
CmpItemKindOperator = {fg = "#73daca"},
CmpItemKindProperty = {fg = "#73daca"},
CmpItemKindReference = {fg = "#bb9af7"},
CmpItemKindSnippet = {fg = "#737aa2"},
CmpItemKindStruct = {fg = "#ff9e64"},
CmpItemKindTabnine = {fg = "#ca42f0"},
CmpItemKindText = {fg = "#c0caf5"},
CmpItemKindTypeParameter = {fg = "#73daca"},
CmpItemKindUnit = {fg = "#ff9e64"},
CmpItemKindValue = {fg = "#bb9af7"},
CmpItemKindVariable = {fg = "#bb9af7"},
CmpItemMenu = {fg = "#565f89"},
CmpItemMenuDefault = {fg = "#c0caf5"},
ColorColumn = {bg = "#000000"},
Comment = {fg = "#565f89", italic = true},
DiagnosticUnnecessary = {link = "Comment"},
LirEmptyDirText = {link = "Comment"},
NvimTreeEmptyFolderName = {link = "Comment"},
NvimTreeGitIgnored = {link = "Comment"},
WhichKeySeperator = {link = "Comment"},
luaComment = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@lsp.type.comment"] = {link = "Comment"},
Conceal = {fg = "#737aa2"},
Conditional = {fg = "#ff9aef", bold = true},
Label = {link = "Conditional"},
Statement = {link = "Conditional"},
luaCond = {link = "Conditional"},
luaCondElse = {link = "Conditional"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#ff8994", bold = true},
Character = {link = "Constant"},
Exception = {link = "Constant"},
Float = {link = "Constant"},
luaConstant = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
["@text.reference"] = {link = "Constant"},
CratesNvimLoading = {fg = "#0db9d7"},
CratesNvimVersion = {fg = "#0db9d7"},
Cursor = {fg = "#1a1b26", bg = "#c0caf5"},
CursorColumn = {bg = "#292e42"},
NvimTreeCursorColumn = {link = "CursorColumn"},
CursorIM = {fg = "#1a1b26", bg = "#c0caf5"},
CursorLine = {bg = "#292e42"},
NvimTreeCursorLine = {link = "CursorLine"},
CursorLineNr = {fg = "#737aa2"},
NvimTreeCursorLineNr = {link = "CursorLineNr"},
["@debug"] = {link = "Debug"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#ffbfe7", bold = true},
NvimArrow = {link = "Delimiter"},
NvimColon = {link = "Delimiter"},
NvimComma = {link = "Delimiter"},
NvimParenthesis = {link = "Delimiter"},
markdownIdDelimiter = {link = "Delimiter"},
markdownLinkDelimiter = {link = "Delimiter"},
["@punctuation"] = {link = "Delimiter"},
["@punctuation.delimeter"] = {link = "Delimiter"},
["@punctuation.special"] = {link = "Delimiter"},
DevIconAi = {fg = "#cbcb41"},
DevIconAwk = {fg = "#4d5a5e"},
DevIconBabelrc = {fg = "#cbcb41"},
DevIconBash = {fg = "#89e051"},
DevIconBashProfile = {fg = "#89e051"},
DevIconBashrc = {fg = "#89e051"},
DevIconBat = {fg = "#c1f12e"},
DevIconBazel = {fg = "#89e051"},
DevIconBazelBuild = {fg = "#89e051"},
DevIconBazelWorkspace = {fg = "#89e051"},
DevIconBinaryGLTF = {fg = "#ffb13b"},
DevIconBmp = {fg = "#a074c4"},
DevIconBrewfile = {fg = "#701516"},
DevIconBzl = {fg = "#89e051"},
DevIconC = {fg = "#599eff"},
DevIconCMake = {fg = "#6d8086"},
DevIconCMakeLists = {fg = "#6d8086"},
DevIconCPlusPlus = {fg = "#f34b7d"},
DevIconCjs = {fg = "#cbcb41"},
DevIconClojure = {fg = "#8dc149"},
DevIconClojureC = {fg = "#8dc149"},
DevIconClojureDart = {fg = "#519aba"},
DevIconClojureJS = {fg = "#519aba"},
DevIconCobol = {fg = "#005ca5"},
DevIconCoffee = {fg = "#cbcb41"},
DevIconConf = {fg = "#6d8086"},
DevIconConfigRu = {fg = "#701516"},
DevIconConfiguration = {fg = "#ececec"},
DevIconCp = {fg = "#519aba"},
DevIconCpp = {fg = "#519aba"},
DevIconCrystal = {fg = "#c8c8c8"},
DevIconCs = {fg = "#596706"},
DevIconCsh = {fg = "#4d5a5e"},
DevIconCson = {fg = "#cbcb41"},
DevIconCss = {fg = "#42a5f5"},
DevIconCsv = {fg = "#89e051"},
DevIconCxx = {fg = "#519aba"},
DevIconD = {fg = "#427819"},
DevIconDart = {fg = "#03589c"},
DevIconDb = {fg = "#dad8d8"},
DevIconDefault = {fg = "#6d8086"},
DevIconDesktopEntry = {fg = "#563d7c"},
DevIconDiff = {fg = "#41535b"},
DevIconDoc = {fg = "#185abd"},
DevIconDockerfile = {fg = "#458ee6"},
DevIconDocx = {fg = "#185abd"},
DevIconDrools = {fg = "#ffafaf"},
DevIconDropbox = {fg = "#0061fe"},
DevIconDsStore = {fg = "#41535b"},
DevIconDump = {fg = "#dad8d8"},
DevIconEdn = {fg = "#519aba"},
DevIconEex = {fg = "#a074c4"},
DevIconEjs = {fg = "#cbcb41"},
DevIconElm = {fg = "#519aba"},
DevIconEnv = {fg = "#faf743"},
DevIconEpp = {fg = "#ffa61a"},
DevIconErb = {fg = "#701516"},
DevIconErl = {fg = "#b83998"},
DevIconEslintrc = {fg = "#4b32c3"},
DevIconEx = {fg = "#a074c4"},
DevIconExs = {fg = "#a074c4"},
DevIconFavicon = {fg = "#cbcb41"},
DevIconFennel = {fg = "#fff3d7"},
DevIconFish = {fg = "#4d5a5e"},
DevIconFortran = {fg = "#734f96"},
DevIconFs = {fg = "#519aba"},
DevIconFsharp = {fg = "#519aba"},
DevIconFsi = {fg = "#519aba"},
DevIconFsscript = {fg = "#519aba"},
DevIconFsx = {fg = "#519aba"},
DevIconGDScript = {fg = "#6d8086"},
DevIconGemfile = {fg = "#701516"},
DevIconGemspec = {fg = "#701516"},
DevIconGif = {fg = "#a074c4"},
DevIconGitAttributes = {fg = "#41535b"},
DevIconGitCommit = {fg = "#41535b"},
DevIconGitConfig = {fg = "#41535b"},
DevIconGitIgnore = {fg = "#41535b"},
DevIconGitLogo = {fg = "#f14c28"},
DevIconGitModules = {fg = "#41535b"},
DevIconGitlabCI = {fg = "#e24329"},
DevIconGo = {fg = "#519aba"},
DevIconGodotProject = {fg = "#6d8086"},
DevIconGraphQL = {fg = "#e535ab"},
DevIconGruntfile = {fg = "#e37933"},
DevIconGulpfile = {fg = "#cc3e44"},
DevIconGvimrc = {fg = "#019833"},
DevIconH = {fg = "#a074c4"},
DevIconHaml = {fg = "#eaeae1"},
DevIconHbs = {fg = "#f0772b"},
DevIconHeex = {fg = "#a074c4"},
DevIconHh = {fg = "#a074c4"},
DevIconHpp = {fg = "#a074c4"},
DevIconHrl = {fg = "#b83998"},
DevIconHs = {fg = "#a074c4"},
DevIconHtm = {fg = "#e34c26"},
DevIconHtml = {fg = "#e44d26"},
DevIconHxx = {fg = "#a074c4"},
DevIconIco = {fg = "#cbcb41"},
DevIconImportConfiguration = {fg = "#ececec"},
DevIconIni = {fg = "#6d8086"},
DevIconJava = {fg = "#cc3e44"},
DevIconJavaScriptReactSpec = {fg = "#20c2e3"},
DevIconJavaScriptReactTest = {fg = "#20c2e3"},
DevIconJl = {fg = "#a270ba"},
DevIconJpeg = {fg = "#a074c4"},
DevIconJpg = {fg = "#a074c4"},
DevIconJs = {fg = "#cbcb41"},
DevIconJson = {fg = "#cbcb41"},
DevIconJson5 = {fg = "#cbcb41"},
DevIconJsx = {fg = "#20c2e3"},
DevIconKotlin = {fg = "#7f52ff"},
DevIconKotlinScript = {fg = "#7f52ff"},
DevIconKsh = {fg = "#4d5a5e"},
DevIconLeex = {fg = "#a074c4"},
DevIconLess = {fg = "#563d7c"},
DevIconLhs = {fg = "#a074c4"},
DevIconLicense = {fg = "#cbcb41"},
DevIconLiquid = {fg = "#95bf47"},
DevIconLock = {fg = "#bbbbbb"},
DevIconLog = {fg = "#ffffff"},
DevIconLua = {fg = "#51a0cf"},
DevIconLuau = {fg = "#51a0cf"},
DevIconMakefile = {fg = "#6d8086"},
DevIconMarkdown = {fg = "#519aba"},
DevIconMaterial = {fg = "#b83998"},
DevIconMd = {fg = "#ffffff"},
DevIconMdx = {fg = "#519aba"},
DevIconMint = {fg = "#87c095"},
DevIconMixLock = {fg = "#a074c4"},
DevIconMjs = {fg = "#f1e05a"},
DevIconMl = {fg = "#e37933"},
DevIconMli = {fg = "#e37933"},
DevIconMotoko = {fg = "#9772fb"},
DevIconMustache = {fg = "#e37933"},
DevIconNPMIgnore = {fg = "#e8274b"},
DevIconNPMrc = {fg = "#e8274b"},
DevIconNim = {fg = "#f3d400"},
DevIconNix = {fg = "#7ebae4"},
DevIconNodeModules = {fg = "#e8274b"},
DevIconOPUS = {fg = "#f88a02"},
DevIconOpenTypeFont = {fg = "#ececec"},
DevIconOrgMode = {fg = "#77aa99"},
DevIconPackageJson = {fg = "#e8274b"},
DevIconPackageLockJson = {fg = "#7a0d21"},
DevIconPackedResource = {fg = "#6d8086"},
DevIconPdf = {fg = "#b30b00"},
DevIconPhp = {fg = "#a074c4"},
DevIconPl = {fg = "#519aba"},
DevIconPm = {fg = "#519aba"},
DevIconPng = {fg = "#a074c4"},
DevIconPp = {fg = "#ffa61a"},
DevIconPpt = {fg = "#cb4a32"},
DevIconPrisma = {fg = "#ffffff"},
DevIconProcfile = {fg = "#a074c4"},
DevIconProlog = {fg = "#e4b854"},
DevIconPsManifestfile = {fg = "#6975c4"},
DevIconPsScriptModulefile = {fg = "#6975c4"},
DevIconPsScriptfile = {fg = "#4273ca"},
DevIconPsb = {fg = "#519aba"},
DevIconPsd = {fg = "#519aba"},
DevIconPy = {fg = "#ffbc03"},
DevIconPyc = {fg = "#ffe291"},
DevIconPyd = {fg = "#ffe291"},
DevIconPyo = {fg = "#ffe291"},
DevIconQuery = {fg = "#90a850"},
DevIconR = {fg = "#358a5b"},
DevIconRake = {fg = "#701516"},
DevIconRakefile = {fg = "#701516"},
DevIconRb = {fg = "#701516"},
DevIconReScript = {fg = "#cc3e44"},
DevIconReScriptInterface = {fg = "#f55385"},
DevIconRlib = {fg = "#dea584"},
DevIconRmd = {fg = "#519aba"},
DevIconRproj = {fg = "#358a5b"},
DevIconRs = {fg = "#dea584"},
DevIconRss = {fg = "#fb9d3b"},
DevIconSass = {fg = "#f55385"},
DevIconScala = {fg = "#cc3e44"},
DevIconScheme = {fg = "#000000"},
DevIconScss = {fg = "#f55385"},
DevIconSettingsJson = {fg = "#854cc7"},
DevIconSh = {fg = "#4d5a5e"},
DevIconSig = {fg = "#e37933"},
DevIconSlim = {fg = "#e34c26"},
DevIconSln = {fg = "#854cc7"},
DevIconSml = {fg = "#e37933"},
DevIconSolidity = {fg = "#519aba"},
DevIconSpecJs = {fg = "#cbcb41"},
DevIconSpecTs = {fg = "#519aba"},
DevIconSql = {fg = "#dad8d8"},
DevIconStyl = {fg = "#8dc149"},
DevIconSuo = {fg = "#854cc7"},
DevIconSvelte = {fg = "#ff3e00"},
DevIconSvg = {fg = "#ffb13b"},
DevIconSwift = {fg = "#e37933"},
DevIconSystemVerilog = {fg = "#019833"},
DevIconTFVars = {fg = "#5f43e9"},
DevIconTcl = {fg = "#1e5cb3"},
DevIconTerminal = {fg = "#31b53e"},
DevIconTerraform = {fg = "#5f43e9"},
DevIconTestJs = {fg = "#cbcb41"},
DevIconTestTs = {fg = "#519aba"},
DevIconTex = {fg = "#3d6117"},
DevIconTextResource = {fg = "#cbcb41"},
DevIconTextScene = {fg = "#a074c4"},
DevIconToml = {fg = "#6d8086"},
DevIconTor = {fg = "#519aba"},
DevIconTs = {fg = "#519aba"},
DevIconTsx = {fg = "#1354bf"},
DevIconTwig = {fg = "#8dc149"},
DevIconTxt = {fg = "#89e051"},
DevIconTypeScriptReactSpec = {fg = "#1354bf"},
DevIconTypeScriptReactTest = {fg = "#1354bf"},
DevIconVHDL = {fg = "#019833"},
DevIconVagrantfile = {fg = "#1563ff"},
DevIconVala = {fg = "#7239b3"},
DevIconVerilog = {fg = "#019833"},
DevIconVim = {fg = "#019833"},
DevIconVimrc = {fg = "#019833"},
DevIconVue = {fg = "#8dc149"},
DevIconWasm = {fg = "#5c4cdb"},
DevIconWebmanifest = {fg = "#f1e05a"},
DevIconWebp = {fg = "#a074c4"},
DevIconWebpack = {fg = "#519aba"},
DevIconXcPlayground = {fg = "#e37933"},
DevIconXls = {fg = "#207245"},
DevIconXlsx = {fg = "#207245"},
DevIconXml = {fg = "#e37933"},
DevIconXul = {fg = "#e37933"},
DevIconYaml = {fg = "#6d8086"},
DevIconYml = {fg = "#6d8086"},
DevIconZig = {fg = "#f69a1b"},
DevIconZsh = {fg = "#89e051"},
DevIconZshenv = {fg = "#89e051"},
DevIconZshprofile = {fg = "#89e051"},
DevIconZshrc = {fg = "#89e051"},
DevIconsbt = {fg = "#cc3e44"},
DiagnosticDeprecated = {sp = "red", strikethrough = true},
DiagnosticError = {fg = "#db4b4b"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
LspDiagnosticsError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#1abc9c"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
LspDiagnosticsHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#0db9d7"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticSignInformation = {link = "DiagnosticInfo"},
LspDiagnosticsInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "lightgreen"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticOther = {fg = "#9d7cd8"},
DiagnosticSignOther = {link = "DiagnosticOther"},
DiagnosticUnderlineError = {sp = "#db4b4b", undercurl = true},
LspDiagnosticsUnderlineError = {link = "DiagnosticUnderlineError"},
DiagnosticUnderlineHint = {sp = "#1abc9c", undercurl = true},
LspDiagnosticsUnderlineHint = {link = "DiagnosticUnderlineHint"},
DiagnosticUnderlineInfo = {sp = "#0db9d7", undercurl = true},
LspDiagnosticsUnderlineInfo = {link = "DiagnosticUnderlineInfo"},
LspDiagnosticsUnderlineInformation = {link = "DiagnosticUnderlineInfo"},
DiagnosticUnderlineOk = {sp = "lightgreen", underline = true},
DiagnosticUnderlineWarn = {sp = "#e0af68", undercurl = true},
LspDiagnosticsUnderlineWarning = {link = "DiagnosticUnderlineWarn"},
DiagnosticVirtualTextError = {fg = "#db4b4b", bg = "#2d202a"},
LspDiagnosticsVirtualTextError = {link = "DiagnosticVirtualTextError"},
DiagnosticVirtualTextHint = {fg = "#1abc9c", bg = "#1a2b32"},
LspDiagnosticsVirtualTextHint = {link = "DiagnosticVirtualTextHint"},
DiagnosticVirtualTextInfo = {fg = "#0db9d7", bg = "#192b38"},
LspDiagnosticsVirtualTextInfo = {link = "DiagnosticVirtualTextInfo"},
LspDiagnosticsVirtualTextInformation = {link = "DiagnosticVirtualTextInfo"},
DiagnosticVirtualTextWarn = {fg = "#e0af68", bg = "#2e2a2d"},
LspDiagnosticsVirtualTextWarning = {link = "DiagnosticVirtualTextWarn"},
DiagnosticWarn = {fg = "#e0af68"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarning = {link = "DiagnosticWarn"},
LspDiagnosticsWarning = {link = "DiagnosticWarn"},
DiffAdd = {bg = "#41a6b5"},
DiffChange = {bg = "#394b70"},
DiffDelete = {bg = "#db4b4b"},
DiffText = {bg = "#394b70"},
Directory = {fg = "#e0af68"},
NvimTreeFolderIcon = {link = "Directory"},
NvimTreeSymlinkFolderName = {link = "Directory"},
EndOfBuffer = {fg = "#1a1b26"},
Error = {fg = "#db4b4b", bold = true},
NvimInvalid = {link = "Error"},
luaError = {link = "Error"},
luaParenError = {link = "Error"},
ErrorMsg = {fg = "#db4b4b", bg = "#1a1b26", bold = true},
NvimInvalidSpacing = {link = "ErrorMsg"},
["@exception"] = {link = "Exception"},
EyelinerPrimary = {fg = "#ff00ff", bold = true},
EyelinerSecondary = {fg = "#00ffff", bold = true},
["@float"] = {link = "Float"},
FloatBorder = {fg = "#3d59a1", bg = "#16161e"},
BqfPreviewBorder = {link = "FloatBorder"},
WhichKeyBorder = {link = "FloatBorder"},
FloatShadow = {bg = "black", blend = 80},
FloatShadowThrough = {bg = "black", blend = 100},
FoldColumn = {fg = "#565f89", bg = "#1a1b26"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#7aa2f7", bg = "#3b4261"},
Function = {fg = "#6ea2f7", bold = true},
Debug = {link = "Function"},
luaFunction = {link = "Function"},
luaMetaMethod = {link = "Function"},
["@function"] = {link = "Function"},
["@function.call"] = {link = "Function"},
["@lsp.type.decorator"] = {link = "Function"},
["@lsp.type.function"] = {link = "Function"},
["@lsp.type.method"] = {link = "Function"},
["@method"] = {link = "Function"},
["@method.call"] = {link = "Function"},
GitSignsAdd = {fg = "#266d6a"},
GitSignsAddInline = {},
GitSignsAddLn = {},
GitSignsAddLnInline = {},
GitSignsAddNr = {},
GitSignsAddPreview = {},
GitSignsChange = {fg = "#536c9e"},
GitSignsChangeInline = {},
GitSignsChangeLn = {},
GitSignsChangeLnInline = {},
GitSignsChangeNr = {},
GitSignsChangedelete = {},
GitSignsChangedeleteLn = {},
GitSignsChangedeleteNr = {},
GitSignsCurrentLineBlame = {},
GitSignsDelete = {fg = "#b2555b"},
GitSignsDeleteInline = {},
GitSignsDeleteLnInline = {},
GitSignsDeleteNr = {},
GitSignsDeletePreview = {},
GitSignsDeleteVirtLn = {},
GitSignsDeleteVirtLnInLine = {},
GitSignsStagedAdd = {fg = "#133635"},
GitSignsStagedAddLn = {bg = "#41a6b5"},
GitSignsStagedAddNr = {fg = "#133635"},
GitSignsStagedChange = {fg = "#29364f"},
GitSignsStagedChangeLn = {bg = "#394b70"},
GitSignsStagedChangeNr = {fg = "#29364f"},
GitSignsStagedChangedelete = {fg = "#29364f"},
GitSignsStagedChangedeleteLn = {bg = "#394b70"},
GitSignsStagedChangedeleteNr = {fg = "#29364f"},
GitSignsStagedDelete = {fg = "#592a2d"},
GitSignsStagedDeleteNr = {fg = "#592a2d"},
GitSignsStagedTopdelete = {fg = "#592a2d"},
GitSignsStagedTopdeleteNr = {fg = "#592a2d"},
GitSignsTopdelete = {},
GitSignsTopdeleteNr = {},
GitSignsUntracked = {},
GitSignsUntrackedLn = {},
GitSignsUntrackedNr = {},
GitSignsVirtLnum = {},
HopNextKey = {fg = "#ff007c"},
HopNextKey1 = {fg = "#0db9d7"},
HopNextKey2 = {fg = "#164a5b"},
HopPreview = {fg = "#c7ba7d"},
HopUnmatched = {fg = "#545c7e"},
Identifier = {fg = "#f2e1d1"},
NvimIdentifier = {link = "Identifier"},
luaFunc = {link = "Identifier"},
["@lsp.type.interface"] = {link = "Identifier"},
["@symbol"] = {link = "Identifier"},
["@tag.attribute"] = {link = "Identifier"},
Ignore = {fg = "bg"},
IlluminatedWordRead = {underline = true},
IlluminatedWordText = {underline = true},
IlluminatedWordWrite = {underline = true},
IncSearch = {fg = "#000000", bg = "#ff9e64"},
CurSearch = {link = "IncSearch"},
Include = {fg = "#85dff8"},
Define = {link = "Include"},
PreProc = {link = "Include"},
markdownRule = {link = "Include"},
["@include"] = {link = "Include"},
["@namespace"] = {link = "Include"},
["@preproc"] = {link = "Include"},
IndentBlanklineChar = {fg = "#3b4261"},
IndentBlanklineContextChar = {fg = "#737aa2"},
IndentBlanklineContextStart = {sp = "#bb9af7", underline = true},
IndentBlanklineSpaceChar = {fg = "#3b4261", nocombine = true},
IndentBlanklineSpaceCharBlankline = {fg = "#3b4261", nocombine = true},
Italic = {italic = true},
markdownItalic = {link = "Italic"},
["@text.emphasis"] = {link = "Italic"},
Keyword = {fg = "#ff9aef", bold = true},
["@keyword"] = {link = "Keyword"},
["@keyword.function"] = {link = "Keyword"},
["@keyword.operator"] = {link = "Keyword"},
["@keyword.return"] = {link = "Keyword"},
["@lsp.type.keyword"] = {link = "Keyword"},
luaLabel = {link = "Label"},
["@label"] = {link = "Label"},
LineNr = {fg = "#3b4261"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
NvimTreeLineNr = {link = "LineNr"},
LirDir = {fg = "#7aa2f7"},
LirFloatNormal = {fg = "#a9b1d6", bg = "#16161e"},
LirSymLink = {fg = "#7dcfff"},
LspCodeLens = {fg = "#565f89", italic = true},
LspCodeLensSeparator = {fg = "#565f89", italic = true},
LspInfoBorder = {},
LspInfoFiletype = {},
LspInfoList = {},
LspInfoTip = {},
LspInfoTitle = {},
LspReferenceRead = {bg = "#3b4261"},
LspReferenceText = {bg = "#3b4261"},
LspReferenceWrite = {bg = "#3b4261"},
Macro = {fg = "#df71e6", bold = true},
PreCondit = {link = "Macro"},
StorageClass = {link = "Macro"},
["@function.macro"] = {link = "Macro"},
["@lsp.type.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
["@text.environment"] = {link = "Macro"},
MatchParen = {fg = "#ff9e64", bold = true},
ModeMsg = {fg = "#a9b1d6", bold = true},
MoreMsg = {fg = "#7aa2f7"},
MsgArea = {fg = "#a9b1d6"},
MsgSeparator = {fg = "#c0caf5", bg = "#1a1b26"},
NavicIconsArray = {fg = "#ff9e64"},
NavicIconsBoolean = {fg = "#ff9e64"},
NavicIconsClass = {fg = "#ff9e64"},
NavicIconsConstant = {fg = "#bb9af7"},
NavicIconsConstructor = {fg = "#ff9e64"},
NavicIconsEnum = {fg = "#ff9e64"},
NavicIconsEnumMember = {fg = "#73daca"},
NavicIconsEvent = {fg = "#ff9e64"},
NavicIconsField = {fg = "#73daca"},
NavicIconsFile = {fg = "#c0caf5"},
NavicIconsFunction = {fg = "#7aa2f7"},
NavicIconsInterface = {fg = "#ff9e64"},
NavicIconsKey = {fg = "#9d7cd8"},
NavicIconsKeyword = {fg = "#9d7cd8"},
NavicIconsMethod = {fg = "#7aa2f7"},
NavicIconsModule = {fg = "#e0af68"},
NavicIconsNamespace = {fg = "#c0caf5"},
NavicIconsNull = {fg = "#ff9e64"},
NavicIconsNumber = {fg = "#ff9e64"},
NavicIconsObject = {fg = "#ff9e64"},
NavicIconsOperator = {fg = "#c0caf5"},
NavicIconsPackage = {fg = "#c0caf5"},
NavicIconsProperty = {fg = "#73daca"},
NavicIconsString = {fg = "#9ece6a"},
NavicIconsStruct = {fg = "#ff9e64"},
NavicIconsTypeParameter = {fg = "#73daca"},
NavicIconsVariable = {fg = "#bb9af7"},
NavicSeparator = {fg = "#a9b1d6"},
NavicText = {fg = "#a9b1d6"},
NonText = {fg = "#545c7e"},
NormalFloat = {fg = "#c0caf5", bg = "#16161e"},
NormalNC = {fg = "#c0caf5"},
NormalSB = {fg = "#c0caf5", bg = "#16161e"},
NotifyDEBUGBody = {fg = "#c0caf5", bg = "#1a1b26"},
NotifyDEBUGBorder = {fg = "#565f89"},
NotifyDEBUGIcon = {fg = "#565f89"},
NotifyDEBUGTitle = {fg = "#565f89"},
NotifyERRORBody = {fg = "#c0caf5", bg = "#1a1b26"},
NotifyERRORBorder = {fg = "#db4b4b"},
NotifyERRORIcon = {fg = "#db4b4b"},
NotifyERRORTitle = {fg = "#db4b4b"},
NotifyINFOBody = {fg = "#c0caf5", bg = "#1a1b26"},
NotifyINFOBorder = {fg = "#0db9d7"},
NotifyINFOIcon = {fg = "#0db9d7"},
NotifyINFOTitle = {fg = "#0db9d7"},
NotifyTRACEBody = {fg = "#c0caf5", bg = "#1a1b26"},
NotifyTRACEBorder = {fg = "#9d7cd8"},
NotifyTRACEIcon = {fg = "#9d7cd8"},
NotifyTRACETitle = {fg = "#9d7cd8"},
NotifyWARNBody = {fg = "#c0caf5", bg = "#1a1b26"},
NotifyWARNBorder = {fg = "#e0af68"},
NotifyWARNIcon = {fg = "#e0af68"},
NotifyWARNTitle = {fg = "#e0af68"},
NullLsInfoBorder = {},
NullLsInfoHeader = {},
NullLsInfoSources = {},
NullLsInfoTitle = {},
Number = {fg = "#ff8994", bold = true},
NvimInternalError = {fg = "red", bg = "red"},
NvimFigureBrace = {link = "NvimInternalError"},
NvimInvalidSingleQuotedUnknownEscape = {link = "NvimInternalError"},
NvimSingleQuotedUnknownEscape = {link = "NvimInternalError"},
NvimNumber = {fg = "#ff8994", bold = true},
NvimTreeBookmark = {fg = "#9ece6a"},
NvimTreeEndOfBuffer = {fg = "#16161e"},
NvimTreeExecFile = {fg = "#9ece6a", italic = true},
NvimTreeFolderName = {fg = "#7aa2f7"},
NvimTreeGitDeleted = {fg = "#b2555b"},
NvimTreeFileDeleted = {link = "NvimTreeGitDeleted"},
NvimTreeGitDirty = {fg = "#536c9e"},
NvimTreeFileDirty = {link = "NvimTreeGitDirty"},
NvimTreeGitMerge = {fg = "#536c9e"},
NvimTreeFileMerge = {link = "NvimTreeGitMerge"},
NvimTreeGitNew = {fg = "#266d6a"},
NvimTreeFileNew = {link = "NvimTreeGitNew"},
NvimTreeGitRenamed = {fg = "#266d6a"},
NvimTreeFileRenamed = {link = "NvimTreeGitRenamed"},
NvimTreeGitStaged = {fg = "#266d6a"},
NvimTreeFileStaged = {link = "NvimTreeGitStaged"},
NvimTreeImageFile = {fg = "#a9b1d6"},
NvimTreeIndentMarker = {fg = "#3b4261"},
NvimTreeLiveFilterPrefix = {fg = "#9d7cd8", bold = true},
NvimTreeLiveFilterValue = {bold = true},
NvimTreeModifiedFile = {fg = "#9ece6a"},
NvimTreeNormal = {fg = "#a9b1d6"},
NvimTreeSignColumn = {link = "NvimTreeNormal"},
NvimTreeNormalNC = {fg = "#a9b1d6"},
NvimTreeOpenedFile = {bg = "#292e42"},
NvimTreeOpenedFolderName = {fg = "#7aa2f7", bold = true, italic = true},
NvimTreeRootFolder = {fg = "#7aa2f7", bold = true},
NvimTreeSpecialFile = {fg = "#9d7cd8", underline = true},
NvimTreeSymlink = {fg = "#7dcfff"},
NvimTreeVertSplit = {fg = "#a9b1d6", bg = "#a9b1d6"},
NvimTreeWinSeparator = {fg = "#16161e", bg = "#16161e"},
NvimTreeWindowPicker = {fg = "#ededed", bg = "#4493c8", bold = true},
Operator = {fg = "#ff9aef", bold = true},
NvimAssignment = {link = "Operator"},
NvimOperator = {link = "Operator"},
luaOperator = {link = "Operator"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#c0caf5", bg = "#16161e"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#16161e"},
PmenuSel = {bg = "#3b4261"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {bg = "#3b4261"},
markdownHeadingRule = {link = "PreProc"},
["@attribute"] = {link = "PreProc"},
Question = {fg = "#7aa2f7"},
QuickFixLine = {bg = "#2d59a1", bold = true},
QuickScopePrimary = {fg = "#ff00ff", bold = true},
QuickScopeSecondary = {fg = "#00ffff", bold = true},
RedrawDebugClear = {bg = "yellow"},
RedrawDebugComposed = {bg = "green"},
RedrawDebugNormal = {reverse = true},
RedrawDebugRecompose = {bg = "red"},
Repeat = {fg = "#ff9aef", bold = true},
luaFor = {link = "Repeat"},
luaRepeat = {link = "Repeat"},
["@repeat"] = {link = "Repeat"},
SLBranchName = {fg = "#c0caf5", bg = "#292e42"},
SLCopilot = {fg = "#6cc644", bg = "#16161e"},
SLGitIcon = {fg = "#e8ab53", bg = "#292e42"},
SLSeparator = {fg = "#292e42", bg = "#16161e"},
Search = {fg = "#c0caf5", bg = "#3d59a1"},
SignColumn = {fg = "#3b4261"},
CursorLineSign = {link = "SignColumn"},
SignColumnSB = {fg = "#3b4261", bg = "#16161e"},
Special = {fg = "#85dff8", bold = true},
markdownEscape = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
["@constructor"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
["@text.math"] = {link = "Special"},
SpecialChar = {fg = "#ff8994", bold = true},
NvimRegister = {link = "SpecialChar"},
NvimStringSpecial = {link = "SpecialChar"},
luaSpecial = {link = "SpecialChar"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
["@text.note"] = {link = "SpecialComment"},
SpecialKey = {fg = "#545c7e", bold = true},
SpellBad = {sp = "#db4b4b", undercurl = true},
SpellCap = {sp = "#e0af68", undercurl = true},
SpellLocal = {sp = "#1abc9c", undercurl = true},
SpellRare = {sp = "#0db9d7", undercurl = true},
luaStatement = {link = "Statement"},
StatusLine = {fg = "#a9b1d6", bg = "#16161e"},
NvimTreeStatusLine = {link = "StatusLine"},
StatusLineNC = {fg = "#3b4261", bg = "#16161e"},
NvimTreeStatusLineNC = {link = "StatusLineNC"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#ffcfe8", bold = true},
NvimString = {link = "String"},
luaString = {link = "String"},
luaString2 = {link = "String"},
["@string"] = {link = "String"},
["@string.regex"] = {link = "String"},
["@text.literal"] = {link = "String"},
luaTable = {link = "Structure"},
["@lsp.type.class"] = {link = "Structure"},
["@lsp.type.struct"] = {link = "Structure"},
Substitute = {fg = "#000000", bg = "#f7768e"},
SymbolsOutlineConnector = {fg = "#737aa2"},
TabLine = {fg = "#3b4261", bg = "#16161e"},
TabLineFill = {bg = "#000000"},
TabLineSel = {fg = "#000000", bg = "#7aa2f7"},
["@tag"] = {link = "Tag"},
TelescopeMatching = {fg = "#1abc9c", bold = true, italic = true},
TelescopeNormal = {fg = "#c0caf5", bg = "#16161e"},
TelescopePreviewHyphen = {fg = "#f7768e"},
TelescopePreviewTitle = {fg = "#ff9e64"},
TelescopePromptCounter = {fg = "#f7768e"},
TelescopePromptPrefix = {fg = "#bb9af7"},
TelescopePromptTitle = {fg = "#ff9e64"},
TelescopeResultsTitle = {fg = "#ff9e64"},
TelescopeSelectionCaret = {fg = "#f7768e", bg = "#2d59a1"},
TermCursor = {fg = "#1a1b26", bg = "#c0caf5"},
TermCursorNC = {fg = "#1a1b26", bg = "#c0caf5"},
Title = {fg = "#7aa2f7", bold = true},
FloatTitle = {link = "Title"},
markdownH1 = {link = "Title"},
markdownH2 = {link = "Title"},
markdownH3 = {link = "Title"},
markdownH4 = {link = "Title"},
markdownH5 = {link = "Title"},
markdownH6 = {link = "Title"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#1a1b26", bg = "#e0af68", bold = true},
luaTodo = {link = "Todo"},
["@text.todo"] = {link = "Todo"},
["@text.warning"] = {link = "Todo"},
TreesitterContext = {bg = "#16161e"},
Type = {fg = "#85dff8", bold = true},
NvimNumberPrefix = {link = "Type"},
NvimOptionSigil = {link = "Type"},
SpecialComment = {link = "Type"},
Structure = {link = "Type"},
Tag = {link = "Type"},
Typedef = {link = "Type"},
markdownId = {link = "Type"},
["@lsp.type.enum"] = {link = "Type"},
["@lsp.type.type"] = {link = "Type"},
["@text.environment.name"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.builtin"] = {link = "Type"},
["@type.qualifier"] = {link = "Type"},
markdownFootnote = {link = "Typedef"},
markdownFootnoteDefinition = {link = "Typedef"},
markdownIdDeclaration = {link = "Typedef"},
["@lsp.type.typeParameter"] = {link = "Typedef"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
Variable = {fg = "#f2e1d1", bold = true},
["@variable"] = {link = "Variable"},
VertSplit = {fg = "#000000"},
Visual = {bg = "#2d59a1"},
BookmarkAnnotationLine = {link = "Visual"},
BookmarkLine = {link = "Visual"},
BqfPreviewRange = {link = "Visual"},
TelescopeSelection = {link = "Visual"},
VisualNOS = {bg = "#2d59a1"},
WarningMsg = {fg = "#e0af68"},
["@text.danger"] = {link = "WarningMsg"},
WhichKey = {fg = "#7dcfff"},
WhichKeyDesc = {fg = "#bb9af7"},
WhichKeyFloat = {bg = "#16161e"},
WhichKeyGroup = {fg = "#7aa2f7"},
WhichKeySeparator = {},
WhichKeyValue = {fg = "#737aa2"},
Whitespace = {fg = "#3b4261"},
WildMenu = {bg = "#2d59a1", bold = true},
WinBar = {fg = "#c0caf5"},
WinBarNC = {link = "WinBar"},
WinSeparator = {fg = "#000000", bold = true},
lCursor = {fg = "#1a1b26", bg = "#c0caf5"},
luaNumber = {fg = "#ff8994", bold = true},
["lualine_a_18_command"] = {fg = "#16161e", bg = "#e0af68"},
["lualine_a_18_inactive"] = {fg = "#7aa2f7", bg = "#16161e"},
["lualine_a_18_insert"] = {fg = "#16161e", bg = "#9ece6a"},
["lualine_a_18_normal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_a_18_replace"] = {fg = "#16161e", bg = "#f7768e"},
["lualine_a_18_terminal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_a_18_visual"] = {fg = "#16161e", bg = "#bb9af7"},
["lualine_a_8_command"] = {fg = "#16161e", bg = "#e0af68"},
["lualine_a_8_inactive"] = {fg = "#7aa2f7", bg = "#16161e"},
["lualine_a_8_insert"] = {fg = "#16161e", bg = "#9ece6a"},
["lualine_a_8_normal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_a_8_replace"] = {fg = "#16161e", bg = "#f7768e"},
["lualine_a_8_terminal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_a_8_visual"] = {fg = "#16161e", bg = "#bb9af7"},
["lualine_a_command"] = {fg = "#16161e", bg = "#e0af68"},
["lualine_a_inactive"] = {fg = "#7aa2f7", bg = "#16161e"},
["lualine_a_insert"] = {fg = "#16161e", bg = "#9ece6a"},
["lualine_a_normal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_a_replace"] = {fg = "#16161e", bg = "#f7768e"},
["lualine_a_visual"] = {fg = "#16161e", bg = "#bb9af7"},
["lualine_b_19_command"] = {fg = "#e0af68", bg = "#3b4261", bold = true},
["lualine_b_19_inactive"] = {fg = "#3b4261", bg = "#16161e", bold = true},
["lualine_b_19_insert"] = {fg = "#9ece6a", bg = "#3b4261", bold = true},
["lualine_b_19_normal"] = {fg = "#7aa2f7", bg = "#3b4261", bold = true},
["lualine_b_19_replace"] = {fg = "#f7768e", bg = "#3b4261", bold = true},
["lualine_b_19_terminal"] = {fg = "#7aa2f7", bg = "#3b4261", bold = true},
["lualine_b_19_visual"] = {fg = "#bb9af7", bg = "#3b4261", bold = true},
["lualine_b_9_command"] = {fg = "#e0af68", bg = "#3b4261", bold = true},
["lualine_b_9_inactive"] = {fg = "#3b4261", bg = "#16161e", bold = true},
["lualine_b_9_insert"] = {fg = "#9ece6a", bg = "#3b4261", bold = true},
["lualine_b_9_normal"] = {fg = "#7aa2f7", bg = "#3b4261", bold = true},
["lualine_b_9_replace"] = {fg = "#f7768e", bg = "#3b4261", bold = true},
["lualine_b_9_terminal"] = {fg = "#7aa2f7", bg = "#3b4261", bold = true},
["lualine_b_9_visual"] = {fg = "#bb9af7", bg = "#3b4261", bold = true},
["lualine_b_command"] = {fg = "#e0af68", bg = "#3b4261"},
["lualine_b_inactive"] = {fg = "#3b4261", bg = "#16161e", bold = true},
["lualine_b_insert"] = {fg = "#9ece6a", bg = "#3b4261"},
["lualine_b_normal"] = {fg = "#7aa2f7", bg = "#3b4261"},
["lualine_b_replace"] = {fg = "#f7768e", bg = "#3b4261"},
["lualine_b_visual"] = {fg = "#bb9af7", bg = "#3b4261"},
["lualine_c_11_command"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_11_inactive"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_11_insert"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_11_normal"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_11_replace"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_11_terminal"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_11_visual"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_21_command"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_21_inactive"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_21_insert"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_21_normal"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_21_replace"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_21_terminal"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_21_visual"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_0_command"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_0_inactive"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_0_insert"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_0_normal"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_0_replace"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_0_terminal"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_0_visual"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_command"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_inactive"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_insert"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_normal"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_replace"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_terminal"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_added_visual"] = {fg = "#98be65", bg = "#16161e"},
["lualine_c_diff_modified_0_command"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_0_inactive"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_0_insert"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_0_normal"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_0_replace"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_0_terminal"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_0_visual"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_command"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_inactive"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_insert"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_normal"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_replace"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_terminal"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_modified_visual"] = {fg = "#ecbe7b", bg = "#16161e"},
["lualine_c_diff_removed_0_command"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_0_inactive"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_0_insert"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_0_normal"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_0_replace"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_0_terminal"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_0_visual"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_command"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_inactive"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_insert"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_normal"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_replace"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_terminal"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_diff_removed_visual"] = {fg = "#ec5f67", bg = "#16161e"},
["lualine_c_inactive"] = {fg = "#3b4261", bg = "#16161e"},
["lualine_c_normal"] = {fg = "#a9b1d6", bg = "#16161e"},
["lualine_x_13_command"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_13_inactive"] = {fg = "#3b4261", bg = "#16161e", bold = true},
["lualine_x_13_insert"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_13_normal"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_13_replace"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_13_terminal"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_13_visual"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_3_command"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_3_inactive"] = {fg = "#3b4261", bg = "#16161e", bold = true},
["lualine_x_3_insert"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_3_normal"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_3_replace"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_3_terminal"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_3_visual"] = {fg = "#a9b1d6", bg = "#16161e", bold = true},
["lualine_x_diagnostics_error_0_command"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_0_inactive"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_0_insert"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_0_normal"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_0_replace"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_0_terminal"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_0_visual"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_command"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_inactive"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_insert"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_normal"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_replace"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_terminal"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_error_visual"] = {fg = "#db4b4b", bg = "#16161e"},
["lualine_x_diagnostics_hint_0_command"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_0_inactive"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_0_insert"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_0_normal"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_0_replace"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_0_terminal"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_0_visual"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_command"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_inactive"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_insert"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_normal"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_replace"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_terminal"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_hint_visual"] = {fg = "#1abc9c", bg = "#16161e"},
["lualine_x_diagnostics_info_0_command"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_0_inactive"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_0_insert"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_0_normal"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_0_replace"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_0_terminal"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_0_visual"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_command"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_inactive"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_insert"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_normal"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_replace"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_terminal"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_info_visual"] = {fg = "#0db9d7", bg = "#16161e"},
["lualine_x_diagnostics_warn_0_command"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_0_inactive"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_0_insert"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_0_normal"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_0_replace"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_0_terminal"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_0_visual"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_command"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_inactive"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_insert"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_normal"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_replace"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_terminal"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_diagnostics_warn_visual"] = {fg = "#e0af68", bg = "#16161e"},
["lualine_x_filetype_DevIconDefault_command"] = {fg = "#6d8086", bg = "#16161e"},
["lualine_x_filetype_DevIconDefault_inactive"] = {fg = "#6d8086", bg = "#16161e"},
["lualine_x_filetype_DevIconDefault_insert"] = {fg = "#6d8086", bg = "#16161e"},
["lualine_x_filetype_DevIconDefault_normal"] = {fg = "#6d8086", bg = "#16161e"},
["lualine_x_filetype_DevIconDefault_replace"] = {fg = "#6d8086", bg = "#16161e"},
["lualine_x_filetype_DevIconDefault_terminal"] = {fg = "#6d8086", bg = "#16161e"},
["lualine_x_filetype_DevIconDefault_visual"] = {fg = "#6d8086", bg = "#16161e"},
["lualine_x_filetype_DevIconLua_command"] = {fg = "#51a0cf", bg = "#16161e"},
["lualine_x_filetype_DevIconLua_inactive"] = {fg = "#51a0cf", bg = "#16161e"},
["lualine_x_filetype_DevIconLua_insert"] = {fg = "#51a0cf", bg = "#16161e"},
["lualine_x_filetype_DevIconLua_normal"] = {fg = "#51a0cf", bg = "#16161e"},
["lualine_x_filetype_DevIconLua_replace"] = {fg = "#51a0cf", bg = "#16161e"},
["lualine_x_filetype_DevIconLua_terminal"] = {fg = "#51a0cf", bg = "#16161e"},
["lualine_x_filetype_DevIconLua_visual"] = {fg = "#51a0cf", bg = "#16161e"},
["lualine_z_progress_0_command"] = {fg = "#16161e", bg = "#e0af68"},
["lualine_z_progress_0_inactive"] = {fg = "#7aa2f7", bg = "#16161e"},
["lualine_z_progress_0_insert"] = {fg = "#16161e", bg = "#9ece6a"},
["lualine_z_progress_0_normal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_z_progress_0_replace"] = {fg = "#16161e", bg = "#f7768e"},
["lualine_z_progress_0_terminal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_z_progress_0_visual"] = {fg = "#16161e", bg = "#bb9af7"},
["lualine_z_progress_command"] = {fg = "#16161e", bg = "#e0af68"},
["lualine_z_progress_inactive"] = {fg = "#7aa2f7", bg = "#16161e"},
["lualine_z_progress_insert"] = {fg = "#16161e", bg = "#9ece6a"},
["lualine_z_progress_normal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_z_progress_replace"] = {fg = "#16161e", bg = "#f7768e"},
["lualine_z_progress_terminal"] = {fg = "#16161e", bg = "#7aa2f7"},
["lualine_z_progress_visual"] = {fg = "#16161e", bg = "#bb9af7"},
markdownBlockquote = {fg = "#ff9e64"},
markdownBoldItalic = {fg = "#e0af68", bold = true, italic = true},
markdownCode = {fg = "#1abc9c"},
markdownCodeBlock = {fg = "#1abc9c"},
markdownCodeDelimiter = {fg = "#1abc9c"},
markdownHeadingDelimiter = {fg = "#ff9e64", bold = true},
markdownLinkText = {fg = "#7dcfff", underline = true},
markdownListMarker = {fg = "#ff9e64", bold = true},
markdownOrderedListMarker = {fg = "#ff9e64", bold = true},
markdownUrl = {fg = "#7dcfff", underline = true},
packerHash = {fg = "#7aa2f7"},
packerOutput = {fg = "#9d7cd8"},
packerRelDate = {fg = "#3b4261"},
packerStatusSuccess = {fg = "#7aa2f7"},
packerString = {fg = "#ff9e64"},
packerSuccess = {fg = "#9ece6a"},
["@boolean"] = {fg = "#ff8994", bold = true},
["@field"] = {fg = "#85dff8", bold = true},
["@number"] = {fg = "#ff8994", bold = true},
["@parameter"] = {fg = "#ff8994", bold = true},
["@variable.parameter"] = {fg = "#ff8994", bold = true},
["@lsp.type.parameter"] = {link = "@parameter"},
["@property"] = {fg = "#85dff8", bold = true},
["@lsp.type.property"] = {link = "@property"},
["@punctuation.bracket"] = {fg = "#ffbfe8", bold = true},
["@punctuation.special.markdown"] = {fg = "#ff9e64", bold = true},
["@tag.delimiter"] = {fg = "#737aa2"},
["@text.literal.markdown_inline"] = {fg = "#7aa2f7", bg = "#414868"},
["@text.strike"] = {strikethrough = true},
["@variable.builtin"] = {fg = "#df71e6", bold = true},
["@lsp.typemod.variable.defaultLibrary"] = {link = "@variable.builtin"},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
